"""ajoute residence principale et frais acquisition immobilier

Revision ID: 1c47c878c90e
Revises: e41ca140636a
Create Date: 2026-09-09 16:04:02.346530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c47c878c90e'
down_revision: Union[str, Sequence[str], None] = 'e41ca140636a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding_immobilier_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frais_acquisition', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('residence_principale', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding_immobilier_details', schema=None) as batch_op:
        batch_op.drop_column('residence_principale')
        batch_op.drop_column('frais_acquisition')

    # ### end Alembic commands ###
