"""ajoute_zone_geo_holdings

Revision ID: 230721d2ebf6
Revises: e7629b1f4b56
Create Date: 2026-08-24 21:10:41.354771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230721d2ebf6'
down_revision: Union[str, Sequence[str], None] = 'e7629b1f4b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_geo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('zone_geo')

    # ### end Alembic commands ###
