"""salaires_multiples_avec_taux_imposition_par_entree

Revision ID: 38389a473a71
Revises: bf227db271ea
Create Date: 2026-08-25 09:22:57.951272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38389a473a71'
down_revision: Union[str, Sequence[str], None] = 'bf227db271ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('taux_imposition_pct', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_salaire_user_annee'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_salaire_user_annee'), ['user_id', 'annee'])
        batch_op.drop_column('taux_imposition_pct')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
