"""ajoute detenteur sur salaire

Revision ID: 3a42a82adf63
Revises: 1c47c878c90e
Create Date: 2026-09-09 16:37:27.156790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a42a82adf63'
down_revision: Union[str, Sequence[str], None] = '1c47c878c90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detenteur_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_salaires_detenteur_id'), ['detenteur_id'], unique=False)
        batch_op.create_foreign_key('fk_salaires_detenteur_id_detenteurs', 'detenteurs', ['detenteur_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.drop_constraint('fk_salaires_detenteur_id_detenteurs', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_salaires_detenteur_id'))
        batch_op.drop_column('detenteur_id')

    # ### end Alembic commands ###
