"""ajoute_detenteurs_quotites_rattachement

Revision ID: 49d48b0cee7b
Revises: fe74a8877ec0
Create Date: 2026-08-21 14:00:00.637550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d48b0cee7b'
down_revision: Union[str, Sequence[str], None] = 'fe74a8877ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detenteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detenteurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detenteurs_user_id'), ['user_id'], unique=False)

    op.create_table('quotites_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('detenteur_id', sa.Integer(), nullable=False),
    sa.Column('quotite_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['detenteur_id'], ['detenteurs.id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holding_id', 'detenteur_id', name='uq_quotite_holding_detenteur')
    )
    with op.batch_alter_table('quotites_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotites_holdings_detenteur_id'), ['detenteur_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotites_holdings_holding_id'), ['holding_id'], unique=False)

    op.create_table('quotites_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('detenteur_id', sa.Integer(), nullable=False),
    sa.Column('quotite_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['detenteur_id'], ['detenteurs.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'detenteur_id', name='uq_quotite_loan_detenteur')
    )
    with op.batch_alter_table('quotites_loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotites_loans_detenteur_id'), ['detenteur_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotites_loans_loan_id'), ['loan_id'], unique=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holding_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_loans_holding_id'), ['holding_id'], unique=False)
        # Nom explicite requis par le mode batch de SQLite (cf. incident déjà rencontré
        # lors de l'adoption d'Alembic, backlog 2.I.4) — un nom auto (`None`) échoue.
        batch_op.create_foreign_key('fk_loans_holding_id_holdings', 'holdings', ['holding_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_holding_id_holdings', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loans_holding_id'))
        batch_op.drop_column('holding_id')

    with op.batch_alter_table('quotites_loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotites_loans_loan_id'))
        batch_op.drop_index(batch_op.f('ix_quotites_loans_detenteur_id'))

    op.drop_table('quotites_loans')
    with op.batch_alter_table('quotites_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotites_holdings_holding_id'))
        batch_op.drop_index(batch_op.f('ix_quotites_holdings_detenteur_id'))

    op.drop_table('quotites_holdings')
    with op.batch_alter_table('detenteurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detenteurs_user_id'))

    op.drop_table('detenteurs')
    # ### end Alembic commands ###
