"""ajoute_lien_partage_et_partage_acces

Revision ID: 4cd4a198eba7
Revises: 230721d2ebf6
Create Date: 2026-08-25 00:04:41.146723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd4a198eba7'
down_revision: Union[str, Sequence[str], None] = '230721d2ebf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liens_partage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('detenteur_id', sa.Integer(), nullable=True),
    sa.Column('inclure_patrimoine_net', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('inclure_repartition', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('inclure_performance', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('inclure_budget', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('inclure_objectifs', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('masquer_valeurs', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detenteur_id'], ['detenteurs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liens_partage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liens_partage_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_liens_partage_user_id'), ['user_id'], unique=False)

    op.create_table('partage_acces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lien_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('resultat', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lien_id'], ['liens_partage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partage_acces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partage_acces_lien_id'), ['lien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partage_acces_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partage_acces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partage_acces_timestamp'))
        batch_op.drop_index(batch_op.f('ix_partage_acces_lien_id'))

    op.drop_table('partage_acces')
    with op.batch_alter_table('liens_partage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liens_partage_user_id'))
        batch_op.drop_index(batch_op.f('ix_liens_partage_token'))

    op.drop_table('liens_partage')
    # ### end Alembic commands ###
