"""ajoute_taux_pct_et_taxonomie_elargie

Revision ID: b3955f16a9f2
Revises: b1a9e68ef94c
Create Date: 2026-08-24 15:31:36.951316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3955f16a9f2'
down_revision: Union[str, Sequence[str], None] = 'b1a9e68ef94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taux_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('taux_pct')

    # ### end Alembic commands ###
