"""ajoute_salaires

Revision ID: bf227db271ea
Revises: 4cd4a198eba7
Create Date: 2026-08-25 08:38:04.850058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf227db271ea'
down_revision: Union[str, Sequence[str], None] = '4cd4a198eba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type_montant', sa.String(), nullable=False),
    sa.Column('periodicite', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('nombre_mois', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'annee', name='uq_salaire_user_annee')
    )
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salaires_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_salaires_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salaires_user_id'))
        batch_op.drop_index(batch_op.f('ix_salaires_annee'))

    op.drop_table('salaires')
    # ### end Alembic commands ###
