"""ajoute_fiche_immobiliere_et_historique_valorisation

Revision ID: c12f3fd357dc
Revises: b3955f16a9f2
Create Date: 2026-08-24 15:54:07.682068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12f3fd357dc'
down_revision: Union[str, Sequence[str], None] = 'b3955f16a9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_immobilier_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('type_location', sa.String(), nullable=True),
    sa.Column('loyer_mensuel', sa.Float(), nullable=True),
    sa.Column('charges_mensuelles', sa.Float(), nullable=True),
    sa.Column('frais_annuels', sa.Float(), nullable=True),
    sa.Column('surface_m2', sa.Float(), nullable=True),
    sa.Column('nb_pieces', sa.Integer(), nullable=True),
    sa.Column('annee_construction', sa.Integer(), nullable=True),
    sa.Column('dpe', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding_immobilier_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_immobilier_details_holding_id'), ['holding_id'], unique=True)

    op.create_table('holding_valuation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('date_valeur', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding_valuation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_valuation_history_holding_id'), ['holding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holding_valuation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_valuation_history_holding_id'))

    op.drop_table('holding_valuation_history')
    with op.batch_alter_table('holding_immobilier_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_immobilier_details_holding_id'))

    op.drop_table('holding_immobilier_details')
    # ### end Alembic commands ###
