"""ajoute_budget_categories_mouvements_regles_cibles

Revision ID: c1d216e8cc3f
Revises: c12f3fd357dc
Create Date: 2026-08-24 19:33:24.495399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d216e8cc3f'
down_revision: Union[str, Sequence[str], None] = 'c12f3fd357dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories_budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nom', 'parent_id', name='uq_categorie_budget_user_nom_parent')
    )
    with op.batch_alter_table('categories_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_budget_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_budget_user_id'), ['user_id'], unique=False)

    op.create_table('budget_cibles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('montant_mensuel', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'categorie_id', name='uq_budget_cible_user_categorie')
    )
    with op.batch_alter_table('budget_cibles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_cibles_user_id'), ['user_id'], unique=False)

    op.create_table('mouvements_bancaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('compte', sa.String(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('categorise_manuellement', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'transaction_id', name='uq_mouvement_bancaire_user_txid')
    )
    with op.batch_alter_table('mouvements_bancaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mouvements_bancaires_categorie_id'), ['categorie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mouvements_bancaires_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mouvements_bancaires_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mouvements_bancaires_user_id'), ['user_id'], unique=False)

    op.create_table('regles_categorisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_budget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regles_categorisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regles_categorisation_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regles_categorisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regles_categorisation_user_id'))

    op.drop_table('regles_categorisation')
    with op.batch_alter_table('mouvements_bancaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mouvements_bancaires_user_id'))
        batch_op.drop_index(batch_op.f('ix_mouvements_bancaires_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_mouvements_bancaires_date'))
        batch_op.drop_index(batch_op.f('ix_mouvements_bancaires_categorie_id'))

    op.drop_table('mouvements_bancaires')
    with op.batch_alter_table('budget_cibles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_cibles_user_id'))

    op.drop_table('budget_cibles')
    with op.batch_alter_table('categories_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_budget_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_budget_parent_id'))

    op.drop_table('categories_budget')
    # ### end Alembic commands ###
