"""supprime_allocation_targets

Revision ID: dbfb7fd6fbff
Revises: 2dbbdad7f71f
Create Date: 2026-08-25 14:38:21.959664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfb7fd6fbff'
down_revision: Union[str, Sequence[str], None] = '2dbbdad7f71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_targets_annee'))
        batch_op.drop_index(batch_op.f('ix_allocation_targets_user_id'))

    op.drop_table('allocation_targets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_targets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('annee', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('categorie', sa.VARCHAR(), nullable=False),
    sa.Column('pourcentage_cible', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'annee', 'type', 'categorie', name=op.f('uq_target_user_annee_type_categorie'))
    )
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_targets_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_targets_annee'), ['annee'], unique=False)

    # ### end Alembic commands ###
