"""ajoute cache logos catalogue

Revision ID: e41ca140636a
Revises: 0ae37889dae2
Create Date: 2026-09-09 13:57:13.145817

Cache PARTAGÉ (pas par foyer, une seule ligne par clé de catalogue) des logos réels
des établissements du catalogue (retour utilisateur du 09/09/2026 : « avoir déjà les
images des établissements affichées » dans le sélecteur, avant même la création d'un
`Etablissement`) — cf. `models.LogoCatalogue`. Nouvelle table plutôt qu'une colonne
sur un modèle existant : ces logos ne sont rattachés à aucun foyer.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41ca140636a'
down_revision: Union[str, Sequence[str], None] = '0ae37889dae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logos_catalogue',
    sa.Column('logo_key', sa.String(), nullable=False),
    sa.Column('logo_png', sa.Text(), nullable=True),
    sa.Column('derniere_tentative_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('logo_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logos_catalogue')
    # ### end Alembic commands ###
