"""ajoute_objectifs_suivis

Revision ID: e7629b1f4b56
Revises: c1d216e8cc3f
Create Date: 2026-08-24 20:49:19.946395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7629b1f4b56'
down_revision: Union[str, Sequence[str], None] = 'c1d216e8cc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('montant_cible', sa.Float(), nullable=False),
    sa.Column('echeance', sa.String(), nullable=False),
    sa.Column('rendement_hypothese_pct', sa.Float(), nullable=False),
    sa.Column('valeur_a_la_creation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectifs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectifs_user_id'), ['user_id'], unique=False)

    op.create_table('objectif_actifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectif_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.ForeignKeyConstraint(['objectif_id'], ['objectifs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objectif_id', 'holding_id', name='uq_objectif_actif')
    )
    with op.batch_alter_table('objectif_actifs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectif_actifs_holding_id'), ['holding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectif_actifs_objectif_id'), ['objectif_id'], unique=False)

    op.create_table('objectif_contributeurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectif_id', sa.Integer(), nullable=False),
    sa.Column('detenteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detenteur_id'], ['detenteurs.id'], ),
    sa.ForeignKeyConstraint(['objectif_id'], ['objectifs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objectif_id', 'detenteur_id', name='uq_objectif_contributeur')
    )
    with op.batch_alter_table('objectif_contributeurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectif_contributeurs_detenteur_id'), ['detenteur_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectif_contributeurs_objectif_id'), ['objectif_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectif_contributeurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectif_contributeurs_objectif_id'))
        batch_op.drop_index(batch_op.f('ix_objectif_contributeurs_detenteur_id'))

    op.drop_table('objectif_contributeurs')
    with op.batch_alter_table('objectif_actifs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectif_actifs_objectif_id'))
        batch_op.drop_index(batch_op.f('ix_objectif_actifs_holding_id'))

    op.drop_table('objectif_actifs')
    with op.batch_alter_table('objectifs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectifs_user_id'))

    op.drop_table('objectifs')
    # ### end Alembic commands ###
