"""baseline_milestone_2b

Revision ID: fe74a8877ec0
Revises: 
Create Date: 2026-08-20 16:21:06.328836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe74a8877ec0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('poids', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'type', 'categorie', name='uq_fund_comp_ticker_type_categorie')
    )
    with op.batch_alter_table('fund_composition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_composition_ticker'), ['ticker'], unique=False)

    op.create_table('fund_composition_brute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('poids', sa.Float(), nullable=False),
    sa.Column('derniere_maj', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'type', 'categorie', name='uq_fund_comp_brute_ticker_type_categorie')
    )
    with op.batch_alter_table('fund_composition_brute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_composition_brute_ticker'), ['ticker'], unique=False)

    op.create_table('fund_top_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('holding_symbol', sa.String(), nullable=False),
    sa.Column('holding_nom', sa.String(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=False),
    sa.Column('pays', sa.String(), nullable=True),
    sa.Column('secteur', sa.String(), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'holding_symbol', name='uq_fund_top_holding_ticker_symbol')
    )
    with op.batch_alter_table('fund_top_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_top_holdings_ticker'), ['ticker'], unique=False)

    op.create_table('historique_cache',
    sa.Column('cle', sa.String(), nullable=False),
    sa.Column('contenu_json', sa.String(), nullable=False),
    sa.Column('derniere_maj', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('market_data_cache',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prix_actuel', sa.Float(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('secteur', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('erreur', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frais_gestion_pct', sa.Float(), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('parametres',
    sa.Column('cle', sa.String(), nullable=False),
    sa.Column('valeur', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('scheduled_job_config',
    sa.Column('job_key', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('intervalle_heures', sa.Float(), nullable=False),
    sa.Column('derniere_execution', sa.DateTime(), nullable=True),
    sa.Column('dernier_statut', sa.String(), nullable=True),
    sa.Column('dernier_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_key')
    )
    op.create_table('ticker_resolution',
    sa.Column('identifiant', sa.String(), nullable=False),
    sa.Column('ticker_resolu', sa.String(), nullable=True),
    sa.Column('quote_type', sa.String(), nullable=True),
    sa.Column('resolue_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifiant')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('allocation_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('pourcentage_cible', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'annee', 'type', 'categorie', name='uq_target_user_annee_type_categorie')
    )
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_targets_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_allocation_targets_user_id'), ['user_id'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('prix_revient_moyen', sa.Float(), nullable=True),
    sa.Column('compte', sa.String(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('type_actif', sa.String(), nullable=True),
    sa.Column('origine', sa.String(), server_default='reconstruit', nullable=False),
    sa.Column('valeur_estimee', sa.Float(), nullable=True),
    sa.Column('date_valeur_estimee', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('capital_initial', sa.Float(), nullable=False),
    sa.Column('taux_annuel_pct', sa.Float(), nullable=False),
    sa.Column('mensualite', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('duree_mois', sa.Integer(), nullable=False),
    sa.Column('capital_restant_du_manuel', sa.Float(), nullable=True),
    sa.Column('derniere_maj_manuelle', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'user_id', name='uq_transaction_user_transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_datetime_utc'), ['datetime_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('user_parametres',
    sa.Column('cle', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cle', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_parametres')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_symbol'))
        batch_op.drop_index(batch_op.f('ix_transactions_datetime_utc'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))

    op.drop_table('transactions')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))

    op.drop_table('loans')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_user_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_ticker'))

    op.drop_table('holdings')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_targets_user_id'))
        batch_op.drop_index(batch_op.f('ix_allocation_targets_annee'))

    op.drop_table('allocation_targets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('ticker_resolution')
    op.drop_table('scheduled_job_config')
    op.drop_table('parametres')
    op.drop_table('market_data_cache')
    op.drop_table('historique_cache')
    with op.batch_alter_table('fund_top_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_top_holdings_ticker'))

    op.drop_table('fund_top_holdings')
    with op.batch_alter_table('fund_composition_brute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_composition_brute_ticker'))

    op.drop_table('fund_composition_brute')
    with op.batch_alter_table('fund_composition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_composition_ticker'))

    op.drop_table('fund_composition')
    # ### end Alembic commands ###
